AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - _site/**/*
    - "*.gemspec"
    - "gemfiles/*"
    - gems/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - Rakefile
    - Gemfile

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/WordArray:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
