AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - _site/**/*
    - "*.gemspec"
    - "gemfiles/*"
    - gems/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - gemfiles/vendor/bundle/**/*
    - Rakefile
    - Gemfile
    - test/jekyll/**/*
    - test/jekyll/helper.rb
    - test/jekyll/simplecov_custom_profile.rb
    - test/jekyll/test_saas.rb
    - test/test_files.rb
  NewCops: enable

Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/WordArray:
  Enabled: false
